# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ./CodePipelineApp/CodePipelineApp.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build ./CodePipelineApp/CodePipelineApp.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r win-x64 -o ./build_output ./CodePipelineApp/CodePipelineApp.csproj  --self-contained false
      - cp Procfile ./build_output
      
artifacts:
  files:
    - .\build_output\**\*
  discard-paths: no